description: "Template for integrating cabal init with devenv"
preProcess:
  - "nix shell nixpkgs#cabal-install nixpkgs#ghc --command cabal init {{ project-name }}"
postProcess:
  - "[ -d .git ] || git init && git add flake.nix"
  - "direnv allow"
